{{COHORT_CTES}}
SELECT *
FROM FINAL
WHERE AgeAtFirstT1 IS NOT NULL
  AND AgeAtFirstT1 < {{MAX_FIRST_T1_AGE}}
  AND AgeAtLastVisit IS NOT NULL
  AND AgeAtLastVisit < {{MAX_LAST_VISIT_AGE}}
  AND YearsFromFirstT1ToLast IS NOT NULL
  AND YearsFromFirstT1ToLast >= {{MIN_FOLLOWUP_YEARS}}
  AND VisitCount >= {{MIN_VISITS}}
  AND FinalType IN ('T1D', 'IMPUTED_T1D');
